### ISSUE TITLE
reliable server start failed

### ISSUE THREAD

**Issue by robints** [reliablejs/reliable-macaca-slave#30]
###  1. run  macaca doctor:

macaca-doctor version: 1.0.28

  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v4.4.2

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/xxx/Applications/adt-bundle-mac-x86_64/sdk`
  Platforms is set to `/Users/xxx/Applications/adt-bundle-mac-x86_64/sdk/platforms/android-23`
  Android tools is set to `/Users/xxx/Applications/adt-bundle-mac-x86_64/sdk/tools/android`
  ADB tool is set to `/Users/xxx/Applications/adt-bundle-mac-x86_64/sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.15
  ios: 1.0.53

### 2. run reliable-macaca-docker-compose make start
- allocation port 8080.
- test http://127.0.0.1:8080 success.
- $ brew install pkg-config
- $ brew install zeromq
- $ npm install reliable-macaca-slave -g
### 3. run reliable server -m 127.0.0.1:8080 --verbose 

> index.js:58:14 [master] pid:61599 worker fork success
> index.js:61:14 [master] pid:61599 worker online
> /usr/local/lib/node_modules/reliable-macaca-slave/core/slave/channel.js:17
>    constructor(options = {}) {
>                        ^

> SyntaxError: Unexpected token =
>at exports.runInThisContext (vm.js:53:16)
>    at Module._compile (module.js:373:25)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Function.Module._load (module.js:300:12)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)
>    at Object.<anonymous> (/usr/local/lib/node_modules/reliable-macaca->slave/core/slave/index.js:10:17)
>    at Module._compile (module.js:409:26)
>    at Object.Module._extensions..js (module.js:416:10)
> index.js:67:14 [master] pid:61599 worker disconnect
> index.js:58:14 [master] pid:61599 worker fork success
> index.js:71:14 [master] pid:61599 worker exit code: 1 signal: null
> index.js:61:14 [master] pid:61599 worker online

**Comment by robints** [comment]
fixed, node upgrade to 6.9.2.
