### ISSUE TITLE
slave cannot run

### ISSUE THREAD

**Issue by lxing1024** [reliablejs/reliable-macaca-slave#32]
on my mac run slave always return error like below:
/Users/jizhang/reliable-macaca-slave/core/slave/channel.js:17
    constructor(options = {}) {
                        ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jizhang/reliable-macaca-slave/core/slave/index.js:10:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
>> index.js:67:14 [master] pid:40154 worker disconnect
>> index.js:58:14 [master] pid:40154 worker fork success
>> index.js:71:14 [master] pid:40154 worker exit code: 1 signal: null
>> index.js:61:14 [master] pid:40154 worker online

**Comment by ImTomy** [comment]
node version need to use 6.x.x
